### ISSUE TITLE
Restore bindings

### ISSUE THREAD

**Issue by Mace404** [nicoco007/DynamicOpenVR#1]
How do I restore the SteamVR bindings?
It's impossible to revert to the default Beat Saber bindings in SteamVR.
Everytime I try to open the controller settings screen it gives an error about not able to find the DynamicOpenVR folder.
After that error there is no option to select the default binding. 
It looks like you have overridden the default Beat Saber binding wile I used this plugin?
(have removed the plugin since i'm trying to figure out what causes ingame stutters)

**Comment by nicoco007** [comment]
Hey, sorry for taking so long to get back to you.

It might be because there are still some DynamicOpenVR-related files lingering around. Could you try following [the instructions under Removing DynamicOpenVR](https://github.com/nicoco007/DynamicOpenVR/blob/master/TROUBLESHOOTING.md#removing-dynamicopenvr)?
