### ISSUE TITLE
Custom avatars "Left-" and "Right Hand Animation" Bindings

### ISSUE THREAD

**Issue by FakeFace04** [nicoco007/DynamicOpenVR#12]
Hello there!

I have an issue with my avatar not moving  at all. i have tried doing custom bindings for my motion controllers, but it says when i click custom avatars: "Following things not bound "Left Hand Animation"
"Right Hand Animation"" i couldnt find any way to add these bindings so i wanted to ask for help here.

Btw i use the Medion Erazer X1000MR  (Windows Mixed Reality)

I left a screenshot, so it would be easier to see what the problem is.

Thank you in advance!
![Bindings](https://user-images.githubusercontent.com/60146202/72819430-87764b80-3c6d-11ea-8089-a52c0643a3a8.PNG)
![Bindings Custom Avatars](https://user-images.githubusercontent.com/60146202/72819431-880ee200-3c6d-11ea-91dc-b6d9f45ac1c3.png)

**Comment by nicoco007** [comment]
Not binding *Left Hand Animation* and *Right Hand Animation* shouldn't technically cause any issues since they're marked as Recommended, so I'm guessing there's something else that isn't working. Could you please share your latest log? It should be under `C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Logs\_latest.log` or something similar. Also, is it just the avatar that doesn't move or are your sabers also stuck to the ground (i.e. not following your controllers) ?

**Comment by FakeFace04** [comment]
Hey thx for the response ^^

the controllers are working fine after i did the troubleshooting, its just the character standing in the middle of the platform not moving at all. 



[_latest.zip](https://github.com/nicoco007/DynamicOpenVR/files/4119275/_latest.zip)

**Comment by nicoco007** [comment]
Looks like you're still using beta 3 of Custom Avatars which broke after Beat Saber 1.6.0. Could you update to [beta 5](https://github.com/nicoco007/BeatSaberCustomAvatars/releases/tag/v5.0.0-beta.5) and try again?

**Comment by FakeFace04** [comment]
Hey thank you a lot! I didnt even know there was an update out yet. Its working fine now after restarting quite a few times ^^
