### ISSUE TITLE
Haptic feedback frequency way too high on index / vive

### ISSUE THREAD

**Issue by Idlebawb** [nicoco007/DynamicOpenVR#14]
Hi,

ever since I switched to Beat Saber 1.6.2 with current DynamicOpenVR beta I noticed my haptic feedback changed a lot. And it is actually very annoying. Feels and sounds like an electric toothbrush.

I use Index controllers, but I've also heard the same from vive users.
I went through the code and found you have frequency = 150f in TriggerHapticVibration method in HapticVibrationOutput Class.

This seems way too high. I've made a build for myself at 25f and that seems pretty much like how original feedback was.

Also is there any way to set this outside of changing the code and recompiling?

**Comment by nicoco007** [comment]
You're right, it's way too high right now. I've fixed it and it'll be included in the next release.

There isn't a way to adjust it without recompiling since that's not really the point of this mod; this was made so Beat Saber can use SteamVR's new input system, not to customize stuff that couldn't be changed in the first place. While it could definitely be implemented, I don't think it makes sense to put it in here.

**Comment by nicoco007** [comment]
Fixed in [version 0.1.0](https://github.com/nicoco007/DynamicOpenVR/releases/tag/v0.1.0).
