### ISSUE TITLE
Cannot use trigger in Alternative Play mode

### ISSUE THREAD

**Issue by Saroquen** [nicoco007/DynamicOpenVR#19]
It seems that DynamicOpenVR prevents the use of the trigger while in-game (works fine in menus though). In darth maul mode, using the trigger option is supposed to allow splitting and reconnecting the sabers. The creator of Alternative Play suggested removing DynamicOpenVR, saying that it might be taking over the trigger. I completely removed it and the issue disappeared (along with my avatars). Reinstalling DynamicOpenVR returned the issue. I tried rebinding the trigger pull to another button to no avail. I tested this on Index and Vive controllers.

I've seen videos of people using avatars and the alternative play mod though, so I'm not sure if something is wrong on my end.

**Comment by fuyushi** [comment]
I have this issue intermittently in Beat Saber as well. 
When the issue occurs the trigger button action doesn't respond anymore, which is used as sort of a leftclick. But other buttons continue to work - like the menu button to pause mid-song. I even have the trigger action also bound to a regular button (Right controller X on the oculus touch) which also doesn't respond in that case. 
I haven't tried to reproduce the issue but it seems to happen after the HMD was taken off and then on again. Restarting the game fixes the issue.

**Comment by nicoco007** [comment]
It looks like Alternative Play is using Unity's Input class for the trigger value rather than using Beat Saber's code to access it. Unfortunately, because of a limitation in the way methods can be patched, I can't override the value returned by what they're using like what's done with Beat Saber's input. Therefore, for this to work, Alternative Play has to either use Beat Saber's helper methods to get access to the trigger value or implement support for DynamicOpenVR. Sorry if this is a bit technical, essentially there's nothing I can really do on my end.

@fuyushi Unless I misunderstood what you're describing, I believe your problem is different than what is described by @Saroquen since it doesn't seem to be related to Alternative Play. If what you're encountering is indeed not related to that mod, I encourage you to open a new issue.
