### ISSUE TITLE
cant select anythiing

### ISSUE THREAD

**Issue by Mariimu** [nicoco007/DynamicOpenVR#24]
Windows 10
ACERH101 WMR controllers
Cant select anything even after uninstalling your janky mod and re-installing beatsaber
recreate it by just opening the god damn game mate.
[_latest.log](https://github.com/nicoco007/DynamicOpenVR/files/4269994/_latest.log)

**Comment by Mariimu** [comment]
please respond asap its been broke for a week and ive followed your guide to a tee and it broke unrepairably

**Comment by sodiboo** [comment]
Just Uninstalled your mods and cant click on your menu buttons?
Uninstall DynamicOpenVR follow the steps below to remove DynamicOpenVR
Delete the following: (MAKE SURE STEAMVR IS CLOSED)

- Beat Saber\Plugins\DynamicOpenVR.BeatSaber.dll
- Beat Saber\DynamicOpenVr
- Beat Saber\Libs\DynamicOpenVR.dll
- Beat Saber\beatsaber.vrmanifest

Don't forget to make sure your game is using default bindings after this.
If you accidentally left steamvr open whilst doing this, or if it doesn't fix it try restarting steam.

For those who own it on steam:
Close/Exit Steam completely!
and afterwards open your steam vr settings and controllers bindings and make sure the application/game BEAT SABER
is using default bindings!

**Comment by nicoco007** [comment]
Hey, I'm really, REALLY sorry for not answering this earlier. I've been extremely busy with external things beyond my control which left me very little time to work on Custom Avatars. I know this must be extremely frustrating and I'm incredibly sorry this mod has caused your game to completely stop working; obviously this was not my intent when creating this. I hope you were able to figure it out since you first opened this issue.

If you're still having problems, however, I'm unfortunately not sure what to say since following the troubleshooting instructions revert any changes made to your game by DynamicOpenVR. All I have to offer are a few suggestions that may or may not work and to attempt at your own risk. Before doing any of these though I'd suggest you go through the troubleshooting instructions one last time to make sure you haven't missed anything, because the following suggestions are untested.

* Exit both SteamVR and Steam, delete `appconfig.json` and `steamapps.vrmanifest` inside the `config` folder of your Steam installation, then restart Steam & SteamVR/Beat Saber
* Exit SteamVR, move or delete your current Beat Saber folder and install Beat Saber completely clean (if you haven't tried already)
* Reinstall SteamVR

**Comment by Mariimu** [comment]
oh dont worry ii fixed it
sorry if i gave you any trouble

**Comment by nicoco007** [comment]
Oh okay, great! Again, I'm really sorry for causing your game to break.

I'll close this issue since you were able to fix it.
