### ISSUE TITLE
Support for Vive Cosmos controllers

### ISSUE THREAD

**Issue by JarrodMichell** [nicoco007/DynamicOpenVR#3]
Hi, is there any support for vive cosmos controllers?
I had a look at the troubleshooting guide but it didn't really help, my controllers are just glued to the floor when I use this mod.

**Comment by nicoco007** [comment]
Hey! Sorry for taking so long to get back to you. As long as your controllers are supported by SteamVR, there should be no issue. However, since I don't personally own a Vive Cosmos, I wasn't able to make default bindings for those controllers. I've updated [the troubleshooting guide](https://github.com/nicoco007/DynamicOpenVR/blob/master/TROUBLESHOOTING.md) to include information on how to create your own bindings. Could you try following the instructions and tell me if that works?

**Comment by JarrodMichell** [comment]
Okay thank you, It does use steam VR so I'll give it a go soon and let you know the results :)

**Comment by JarrodMichell** [comment]
I managed to get it to work :)
![winrar](https://user-images.githubusercontent.com/37205360/71305963-ee1a0680-242e-11ea-8485-a177e2ab7947.png)
It seems the latest steam vr update fixed my issues.
My only problem now is, how do I choose what avatar is used?
I tried only having 1 avatar file in the custom avatars folder at a time but some avatars would work while others would not.

**Comment by nicoco007** [comment]
When you're in the main menu, there should be a button called "Mods" on the left pane (where the release notes are). Once you press that, there should be an "Avatars" button that brings you to the usual Avatars menu.

![unknown](https://user-images.githubusercontent.com/1349975/71311873-41ba2f00-23f2-11ea-9f9c-aaac439442c5.png)

**Comment by JarrodMichell** [comment]
Oh I see, I'm so blind haha
Thanks for the help 👍
