### ISSUE TITLE
DynamicOpenVr/CustomAvatars not loading Beat Saber Version 1.10

### ISSUE THREAD

**Issue by L3nn0** [nicoco007/DynamicOpenVR#33]
Hi I wanted to install DynamicOpenVr and Custom Avatars but it doesn't load the plugin. I followed your troubleshooting guide and saw that the files that should generate after the first start didn't show up. I'm using a Valve Index with Knuckles controller on Windows 10. Here is my log: [_latest.log](https://github.com/nicoco007/DynamicOpenVR/files/4944746/_latest.log)
I hope you can help me.

**Comment by nicoco007** [comment]
Looks like you installed DynamicOpenVR.BeatSaber and not DynamicOpenVR. Try removing the file `Plugins\DynamicOpenVR.BeatSaber.dll` and installing **only** DynamicOpenVR (you can download it [here](https://github.com/nicoco007/DynamicOpenVR/releases/download/v0.2.1/DynamicOpenVR-v0.2.1-RELEASE.zip)). You should only download DynamicOpenVR.BeatSaber if you are running SteamVR and want finger tracking because it is known to cause problems with certain installations.

**Comment by L3nn0** [comment]
Thanks for the quick respond. I actually wanted to install DynamicOpenVR.BeatSaber because I use Steam Vr and wanted finger tracking. I removed the file `Plugins\DynamicOpenVR.BeatSaber.dll` and added the files for DynamicOpenVR but it still doesn't work. Here is my new log: 
[_latest.log](https://github.com/nicoco007/DynamicOpenVR/files/4949300/_latest.log)

**Comment by nicoco007** [comment]
Looks like it can't find some of the files that come with Custom Avatars. Did you copy both the `Plugins` and `DynamicOpenVR` folders from the Custom Avatars zip?

**Comment by L3nn0** [comment]
Yes I had copied all the files from the Custom Avatars zip. I've gone ahead and reinstall the whole game and mods and now it works thank you for the help.

**Comment by nicoco007** [comment]
Glad you got it sorted out!
