### ISSUE TITLE
Thumbstick actions

### ISSUE THREAD

**Issue by Mace404** [nicoco007/DynamicOpenVR#35]
Hi,

I want to use the thumbstick on the Knuckles controllers for scrolling through pages.
Playlistloader lite adds this functionality (https://github.com/rithik-b/PlaylistLoaderPlugin) but requires some legacy actions set up.
Since DynamicOpenVR takes over the binding, I cannot add legacy actions.

Is it possible you add the thumbstick actions to the Vector2 action set so they can be selected?

**Comment by Mace404** [comment]
reply for activity

**Comment by AngelKing86** [comment]
I have the same problem. Please add this Vector2 Binding to the default knuckles Joystick bindings. Thank you!

**Comment by nicoco007** [comment]
Sorry about the really long wait, I somehow missed this the first time you posted. I'll see what I can do.

**Comment by nicoco007** [comment]
Sorry about the really long wait, I somehow missed this the first time you posted. I'll see what I can do.

Remember that if you don't need finger tracking, you shouldn't install DynamicOpenVR.BeatSaber. If your bindings are being overriden with just DynamicOpenVR installed, that's not normal; please let me know if that's the case.

**Comment by AngelKing86** [comment]
Thank you for your answer. Somehow I didn't realize that it works without DynamicOpenVR.BeatSaber.

I will test this and contact you again. However, the binding should be checked and possibly corrected.

I've already tried to adjust this somehow with the legacy binding in the json data, but then the button just doesn't respond.

Before that it was "ThumbStick Value" as described here [LINK](https://github.com/rithik-b/PlaylistLoaderPlugin#attention-index-users), but I didn't understand how i can tie that to the right action in the game.

That's why I hope you can find a solution. Because there will be several of them having this problem if they use an index controller with finger tracking.

Thank you for your support

**Comment by nicoco007** [comment]
This has been fixed by 5371e51 and will be included in the next release. If you're still having trouble once that's out, feel free to open another issue.

**Comment by nicoco007** [comment]
Forgot to mention that it should work out-of-the-box without having to mess with bindings since I've added the thumbstick action to the default bindings; if you need to change something to get it working, please let me know because that shouldn't happen!

**Comment by nicoco007** [comment]
This is now available in [version 0.3.4](https://github.com/nicoco007/DynamicOpenVR/releases/tag/v0.3.4). Thank you for reporting this!

**Comment by AngelKing86** [comment]
Thank you for the update! All bindings with my controllers now work without any problems! I think this will help a lot of people who use your mod!
